pragma Singleton

import QtQuick
import Quickshell

// Material Design glyphs from the Nerd Font, one family for every icon.
Singleton {
  readonly property string arch: "\uF303"
  readonly property string star: "\u{F04CE}"
  readonly property string starOutline: "\u{F04D2}"
  readonly property string robot: "\u{F06A9}"
  readonly property string memory: "\u{F035B}"
  readonly property string printer: "\u{F042A}"
  readonly property string printerAlert: "\u{F042C}"
  readonly property string printerOff: "\u{F0E5D}"
  readonly property string bluetooth: "\u{F00AF}"
  readonly property string bluetoothConnected: "\u{F00B1}"
  readonly property string bluetoothOff: "\u{F00B2}"
  readonly property string volumeHigh: "\u{F057E}"
  readonly property string volumeMedium: "\u{F0580}"
  readonly property string volumeLow: "\u{F057F}"
  readonly property string volumeOff: "\u{F0581}"
  readonly property string microphone: "\u{F036C}"
  readonly property string microphoneOff: "\u{F036D}"
  readonly property string headphones: "\u{F02CB}"
  readonly property string headset: "\u{F02CE}"
  readonly property string mouse: "\u{F037D}"
  readonly property string keyboard: "\u{F030C}"
  readonly property string phone: "\u{F011C}"
  readonly property string gamepad: "\u{F0296}"
  readonly property string laptop: "\u{F0322}"
  readonly property string speaker: "\u{F04C3}"
  readonly property string monitor: "\u{F0379}"
  readonly property string devices: "\u{F0FB0}"
  readonly property string calendar: "\u{F00ED}"
  readonly property string apps: "\u{F003B}"
  readonly property string clipboard: "\u{F0192}"
  readonly property string power: "\u{F0425}"
  readonly property string lock: "\u{F033E}"
  readonly property string sleep: "\u{F04B2}"
  readonly property string logout: "\u{F0343}"
  readonly property string restart: "\u{F0709}"
  readonly property string refresh: "\u{F0450}"
  readonly property string close: "\u{F0156}"
  readonly property string chevronLeft: "\u{F0141}"
  readonly property string chevronRight: "\u{F0142}"
  readonly property string chevronDown: "\u{F0140}"
  readonly property string chevronUp: "\u{F0143}"
  readonly property string cog: "\u{F0493}"
  readonly property string check: "\u{F012C}"
  readonly property string charging: "\u{F0084}"
  readonly property string wifi4: "\u{F0928}"
  readonly property string wifi3: "\u{F0925}"
  readonly property string wifi2: "\u{F0922}"
  readonly property string wifi1: "\u{F091F}"
  readonly property string wifiOff: "\u{F092E}"
  readonly property string tune: "\u{F062E}"
  readonly property string document: "\u{F09EE}"
  readonly property string bell: "\u{F009A}"
  readonly property string bellOff: "\u{F009B}"
  readonly property string coffee: "\u{F0176}"
  readonly property string play: "\u{F040A}"
  readonly property string pause: "\u{F03E4}"
  readonly property string skipNext: "\u{F04AD}"
  readonly property string skipPrevious: "\u{F04AE}"
  readonly property string music: "\u{F075A}"
  readonly property string ethernet: "\u{F0200}"
}
