services:
  dev:
    image: ch03git.phonak.com/13lbise/devenv:latest
    container_name: devenv
    working_dir: /home/leodev
    command: sleep infinity
    tty: true
    stdin_open: true
    volumes:
       - /home/13lbise/gitrepo/leo_dotfiles:/home/leodev/gitrepo/leo_dotfiles:rw
       - /home/13lbise/andromeda:/home/leodev/andromeda:rw
       - /tmp/.X11-unix:/tmp/.X11-unix:rw
       - /home/13lbise/.Xauthority:/home/leodev/.Xauthority:ro
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/leodev/.Xauthority
      - TERM=xterm-256color
      - COLORTERM=${COLORTERM:-truecolor}
      - AZURE_RESOURCE_NAME=${AZURE_RESOURCE_NAME}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - GITHUB_COPILOT_TOKEN=${GITHUB_COPILOT_TOKEN}
    network_mode: host  # reuse host network for git / ssh convenience
