#!/usr/bin/env python3

import copy
import importlib.util
import json
import os
import subprocess
import tempfile
import textwrap
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[1] / 'system' / 'system-theme-apply.py'
spec = importlib.util.spec_from_file_location('system_theme_apply', SCRIPT)
theme = importlib.util.module_from_spec(spec)
spec.loader.exec_module(theme)

PALETTE = {
    'name': 'Test',
    'colors': {
        'background': '#101010',
        'surface': '#202020',
        'rule': '#303030',
        'foreground': '#f0f0f0',
        'muted': '#a0a0a0',
        'accent': '#00ff88',
        'alert': '#ff0000',
        'warning': '#ffaa00',
        'good': '#88ff00',
    },
    'font': {'family': 'Test Mono', 'size': 13, 'weight': 400},
    'shape': {'radius': 6, 'barHeight': 34},
    'terminal': {'ghosttyTheme': 'Test Theme'},
}

WALKER_BEGIN = '/* leo-theme:begin (generated by system-theme-apply.py) */'
MAKO_BEGIN = '# leo-theme:begin (generated by system-theme-apply.py)'


class RenderTest(unittest.TestCase):
    def setUp(self) -> None:
        self.palette = theme.validate_palette(PALETTE)

    def test_walker_replaces_top_define_colors_on_first_run(self) -> None:
        css = textwrap.dedent('''\
            @define-color background #111111;
            @define-color base #222222;
            @define-color text #333333;

            * {
              color: @text;
            }
            ''')
        result = theme.walker_css(self.palette, css)
        self.assertTrue(result.startswith(WALKER_BEGIN + '\n@define-color background #101010;\n'))
        self.assertIn('@define-color border #303030;\n/* leo-theme:end */\n\n* {\n', result)
        self.assertNotIn('#111111', result)
        self.assertEqual(result.count('@define-color text '), 1)

    def test_walker_replaces_existing_block_and_keeps_the_rest(self) -> None:
        css = textwrap.dedent(f'''\
            /* my theme */
            {WALKER_BEGIN}
            @define-color background #999999;
            /* leo-theme:end */
            @define-color extra #abcdef;
            .box {{ border: 2px solid @border; }}
            ''')
        result = theme.walker_css(self.palette, css)
        self.assertTrue(result.startswith('/* my theme */\n' + WALKER_BEGIN + '\n'))
        self.assertNotIn('#999999', result)
        self.assertIn('/* leo-theme:end */\n@define-color extra #abcdef;\n.box', result)

    def test_outputs_are_idempotent(self) -> None:
        for render, text in (
            (theme.walker_css, '@define-color base #000000;\n\n* {}\n'),
            (theme.mako_config, 'anchor=top-right\nfont=sans 12\n'),
            (theme.ghostty_config, 'font-size = 14\n\ntheme = Old\n\nwindow-padding-x = 4\n'),
        ):
            once = render(self.palette, text)
            self.assertEqual(render(self.palette, once), once)

    def test_mako_removes_duplicate_global_keys_and_keeps_sections(self) -> None:
        config = textwrap.dedent('''\
            anchor=top-right
            border-color=#123456
            font=sans 12
            width=420

            [app-name=foo]
            border-color=#654321
            ''')
        result = theme.mako_config(self.palette, config)
        global_part = result.split('[app-name=foo]')[0]
        self.assertNotIn('#123456', result)
        self.assertNotIn('font=sans', result)
        self.assertEqual(global_part.count('border-color='), 2)  # global + [urgency=critical]
        self.assertIn('border-color=#654321', result.split('[app-name=foo]')[1])
        self.assertLess(result.index(MAKO_BEGIN), result.index('[app-name=foo]'))
        self.assertIn('progress-color=over #00FF88', result)
        self.assertIn('font=Test Mono 14', result)
        self.assertIn('[urgency=critical]\nborder-color=#FF0000\n# leo-theme:end', result)

    def test_mako_removes_duplicates_added_above_existing_block(self) -> None:
        config = theme.mako_config(self.palette, 'anchor=top-right\n')
        config = 'text-color=#abcdef\n' + config
        result = theme.mako_config(self.palette, config)
        self.assertNotIn('#abcdef', result)
        self.assertEqual(result, theme.mako_config(self.palette, 'anchor=top-right\n'))

    def test_ghostty_block_owns_theme_line(self) -> None:
        result = theme.ghostty_config(self.palette, 'a = 1\n\ntheme = Old\n\nb = 2\n')
        self.assertEqual(result, textwrap.dedent(f'''\
            a = 1

            {MAKO_BEGIN}
            theme = Test Theme
            # leo-theme:end

            b = 2
            '''))

    def test_hyprland_uses_rule_for_borders(self) -> None:
        conf = theme.hyprland_conf(self.palette)
        self.assertTrue(conf.startswith('# Generated from palette.json by system-theme-apply.py'))
        self.assertIn('$activeBorderColor = rgb(303030)', conf)
        self.assertIn('$inactiveBorderColor = rgba(30303080)', conf)
        self.assertIn('col.border_active = $activeBorderColor', conf)

    def test_hyprlock_variables_come_from_palette(self) -> None:
        conf = theme.hyprlock_conf(self.palette)
        self.assertIn('$lock_surface = rgb(202020)', conf)
        self.assertIn('$lock_accent = rgb(00FF88)', conf)
        self.assertIn('$lock_muted_hex = ##A0A0A0', conf)
        self.assertIn('$lock_font = Test Mono', conf)
        self.assertIn('$lock_font_size = 13', conf)
        self.assertIn('$lock_hint_size = 11', conf)
        self.assertIn('$lock_clock_size = 54', conf)
        self.assertIn('$lock_card_radius = 12', conf)
        self.assertIn('$lock_input_radius = 6', conf)
        # The generated file must never change authentication or power behaviour.
        self.assertNotIn('auth {', conf)
        self.assertNotIn('onclick', conf)

    def test_login_config_is_local_and_preserves_hash_colours(self) -> None:
        import configparser
        config = configparser.ConfigParser(interpolation=None)
        config.read_string(theme.login_config(self.palette))
        values = config['General']
        self.assertEqual(values['surface'], '#202020')
        self.assertEqual(values['fontFamily'], 'Test Mono')
        self.assertEqual(values['fontSize'], '17')
        self.assertEqual(values['cardRadius'], '12')
        self.assertEqual(values['wallpaper'], 'wallpaper.jpg')
        self.assertNotIn('/home/', theme.login_config(self.palette))

    def test_invalid_colour_names_the_key(self) -> None:
        palette = copy.deepcopy(PALETTE)
        palette['colors']['accent'] = '#12345'
        with self.assertRaisesRegex(theme.PaletteError, r'colors\.accent'):
            theme.validate_palette(palette)

    def test_unterminated_block_is_rejected(self) -> None:
        with self.assertRaises(ValueError):
            theme.walker_css(self.palette, WALKER_BEGIN + '\n@define-color base #000000;\n')


class CommandTest(unittest.TestCase):
    """Run the script against a temporary XDG_CONFIG_HOME."""

    def setUp(self) -> None:
        self.temporary_directory = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary_directory.name)
        self._write('leo/theme/palette.json', json.dumps(PALETTE))
        self._write('walker/themes/leo/style.css', '@define-color base #000000;\n\n* {}\n')
        self._write('mako/config', 'anchor=top-right\nborder-color=#000000\n')
        self._write('ghostty/config', 'theme = Old\n')

    def tearDown(self) -> None:
        self.temporary_directory.cleanup()

    def _write(self, relative: str, text: str) -> None:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

    def _run(self, *args: str) -> subprocess.CompletedProcess:
        env = dict(os.environ, XDG_CONFIG_HOME=str(self.root))
        return subprocess.run([str(SCRIPT), *args], capture_output=True, text=True, env=env, check=False)

    def test_check_reports_then_apply_then_check_is_clean(self) -> None:
        check = self._run('--check')
        self.assertEqual(check.returncode, 1)
        self.assertIn('+@define-color base #202020;', check.stdout)
        self.assertEqual((self.root / 'ghostty/config').read_text(), 'theme = Old\n')

        applied = self._run()
        self.assertEqual(applied.returncode, 0, applied.stderr)
        self.assertIn('rgb(303030)', (self.root / 'leo/theme/hyprland.conf').read_text())
        self.assertIn('$lock_accent = rgb(00FF88)', (self.root / 'leo/theme/hyprlock.conf').read_text())
        self.assertIn('accent=#00FF88', (self.root / 'leo/login/theme.conf.user').read_text())

        again = self._run('--check')
        self.assertEqual(again.returncode, 0, again.stdout)

    def test_invalid_palette_exits_non_zero_with_key(self) -> None:
        palette = copy.deepcopy(PALETTE)
        palette['colors']['rule'] = 'grey'
        self._write('other.json', json.dumps(palette))
        result = self._run('--palette', str(self.root / 'other.json'))
        self.assertEqual(result.returncode, 1)
        self.assertIn('colors.rule', result.stderr)
        self.assertFalse((self.root / 'leo/theme/hyprland.conf').exists())

    def test_unknown_argument_is_rejected(self) -> None:
        self.assertEqual(self._run('--explode').returncode, 2)


if __name__ == '__main__':
    unittest.main()
