#!/usr/bin/env python3
"""Apply ~/.config/leo/theme/palette.json to the desktop, Hyprlock and SDDM.

Usage:
  system-theme-apply.py [--palette PATH] [--check] [--reload]

  --palette PATH  read this palette instead of $XDG_CONFIG_HOME/leo/theme/palette.json
  --check         write nothing; print a diff and exit 1 if any output is out of date
  --reload        after writing, reload Mako and print how to reload the other apps

leo/theme/hyprland.conf is regenerated entirely. Walker, Mako and Ghostty keep
their own config files; only the lines between the leo-theme:begin and
leo-theme:end markers are generated.
"""

from __future__ import annotations

import configparser
import difflib
import io
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Callable

COLOR_KEYS = ('background', 'surface', 'rule', 'foreground', 'muted', 'accent', 'alert', 'warning', 'good')
HEX_COLOR = re.compile(r'^#[0-9A-Fa-f]{6}$')
GENERATED_BY = 'generated by system-theme-apply.py'

WALKER_COLORS = {
    'background': 'background',
    'base': 'surface',
    'foreground': 'muted',
    'text': 'foreground',
    'selected-text': 'accent',
    'border': 'rule',
}
MAKO_KEYS = ('background-color', 'text-color', 'border-color', 'progress-color', 'border-radius', 'font')


class PaletteError(Exception):
    pass


def config_home() -> Path:
    return Path(os.environ.get('XDG_CONFIG_HOME') or Path.home() / '.config')


def _require(section: dict, key: str, kind: type, where: str):
    value = section.get(key)
    if not isinstance(value, kind) or isinstance(value, bool):
        raise PaletteError(f'{where}.{key} must be a {kind.__name__}, got {value!r}')
    return value


def validate_palette(data: object) -> dict:
    """Check the fields the generators use and normalise colours to upper case."""
    if not isinstance(data, dict):
        raise PaletteError('palette must be a JSON object')
    for section in ('colors', 'font', 'shape', 'terminal'):
        if not isinstance(data.get(section), dict):
            raise PaletteError(f'{section} must be an object')

    colors = {}
    for key in COLOR_KEYS:
        value = data['colors'].get(key)
        if not isinstance(value, str) or not HEX_COLOR.match(value):
            raise PaletteError(f'colors.{key} must be #RRGGBB, got {value!r}')
        colors[key] = value.upper()

    family = _require(data['font'], 'family', str, 'font').strip()
    size = _require(data['font'], 'size', int, 'font')
    radius = _require(data['shape'], 'radius', int, 'shape')
    ghostty_theme = _require(data['terminal'], 'ghosttyTheme', str, 'terminal').strip()
    if not family or '\n' in family:
        raise PaletteError(f'font.family must be a non-empty single line, got {family!r}')
    if size <= 0:
        raise PaletteError(f'font.size must be positive, got {size}')
    if radius < 0:
        raise PaletteError(f'shape.radius must not be negative, got {radius}')
    if not ghostty_theme or '\n' in ghostty_theme:
        raise PaletteError(f'terminal.ghosttyTheme must be a non-empty single line, got {ghostty_theme!r}')

    return {
        'colors': colors,
        'font': {'family': family, 'size': size},
        'shape': {'radius': radius},
        'terminal': {'ghosttyTheme': ghostty_theme},
    }


def load_palette(path: Path) -> dict:
    try:
        data = json.loads(path.read_text())
    except FileNotFoundError:
        raise PaletteError(f'{path} does not exist') from None
    except json.JSONDecodeError as error:
        raise PaletteError(f'{path} is not valid JSON: {error}') from None
    return validate_palette(data)


def hex_digits(color: str) -> str:
    return color.lstrip('#')


def hyprland_conf(palette: dict) -> str:
    rule = hex_digits(palette['colors']['rule'])
    return (
        '# Generated from palette.json by system-theme-apply.py. Do not edit by hand:\n'
        '# change ~/.config/leo/theme/palette.json and run system-theme-apply.py.\n'
        '# https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors\n'
        '\n'
        '# Window borders use the rule colour, not the accent.\n'
        f'$activeBorderColor = rgb({rule})\n'
        f'$inactiveBorderColor = rgba({rule}80)\n'
        '\n'
        'general {\n'
        '    col.active_border = $activeBorderColor\n'
        '    col.inactive_border = $inactiveBorderColor\n'
        '}\n'
        '\n'
        'group {\n'
        '    col.border_active = $activeBorderColor\n'
        '}\n'
    )


def hyprlock_conf(palette: dict) -> str:
    """Only theme variables; layout and authentication stay in hyprlock.conf."""
    colors = palette['colors']
    lines = [
        '# Generated from palette.json by system-theme-apply.py. Do not edit by hand.',
        *[f'$lock_{key} = rgb({hex_digits(colors[key])})' for key in (
            'background', 'surface', 'rule', 'foreground', 'muted', 'accent', 'alert', 'warning',
        )],
        # Hyprlang uses ## for a literal #, needed by Pango colour markup.
        f'$lock_muted_hex = #{colors["muted"]}',
        f'$lock_font = {palette["font"]["family"]}',
        # Hyprlock labels use points, while the Qt login theme uses pixels.
        f'$lock_font_size = {round((palette["font"]["size"] + 4) * 0.75)}',
        f'$lock_hint_size = {round((palette["font"]["size"] + 2) * 0.75)}',
        '$lock_clock_size = 54',
        # Pango markup sizes are points * 1024; convert from pixels at 96 DPI.
        f'$lock_input_text_size = {(palette["font"]["size"] + 4) * 768}',
        f'$lock_card_radius = {palette["shape"]["radius"] + 6}',
        f'$lock_input_radius = {palette["shape"]["radius"]}',
    ]
    return '\n'.join(lines) + '\n'


def login_config(palette: dict) -> str:
    """SDDM reads a local copy; it must not depend on the user's private home."""
    config = configparser.ConfigParser(interpolation=None)
    config.optionxform = str
    config['General'] = {
        **{key: palette['colors'][key] for key in (
            'background', 'surface', 'rule', 'foreground', 'muted', 'accent', 'alert',
        )},
        'fontFamily': palette['font']['family'],
        'fontSize': str(palette['font']['size'] + 4),
        'cardRadius': str(palette['shape']['radius'] + 6),
        'inputRadius': str(palette['shape']['radius']),
        'clockSize': '72',
        'wallpaper': 'wallpaper.jpg',
    }
    output = io.StringIO()
    output.write('# Generated from palette.json by system-theme-apply.py.\n')
    config.write(output, space_around_delimiters=False)
    return output.getvalue()


def walker_block(palette: dict) -> list[str]:
    colors = palette['colors']
    return [f'@define-color {name} {colors[role]};' for name, role in WALKER_COLORS.items()]


def mako_block(palette: dict) -> list[str]:
    colors = palette['colors']
    font = palette['font']
    return [
        f"background-color={colors['background']}",
        f"text-color={colors['foreground']}",
        f"border-color={colors['rule']}",
        f"progress-color=over {colors['accent']}",
        f"border-radius={palette['shape']['radius']}",
        f"font={font['family']} {font['size'] + 1}",
        '',
        '# Criteria sections must follow the global options, so keep this block last.',
        '[urgency=critical]',
        f"border-color={colors['alert']}",
    ]


def ghostty_block(palette: dict) -> list[str]:
    return [f"theme = {palette['terminal']['ghosttyTheme']}"]


def replace_block(
    text: str,
    begin: str,
    end: str,
    body: list[str],
    owns: Callable[[str], bool],
    default_slot: Callable[[list[str]], int],
    global_only: bool = False,
) -> str:
    """Put body between the begin/end marker lines and drop duplicates of the lines it owns.

    Without markers the block goes where the first owned line was, or at
    default_slot. With global_only (Mako), only lines before the first
    `[criteria]` header count as duplicates; the block itself ends in a
    section, so lines after it are never global.
    """
    lines = text.splitlines()
    stripped = [line.strip() for line in lines]
    slot = None
    if begin in stripped:
        start = stripped.index(begin)
        if end not in stripped[start + 1:]:
            raise ValueError(f'found "{begin}" without a following "{end}"')
        stop = stripped.index(end, start + 1)
        lines = lines[:start] + lines[stop + 1:]
        slot = start
    elif end in stripped:
        raise ValueError(f'found "{end}" without a preceding "{begin}"')

    kept: list[str] = []
    first_removed = None
    in_section = False
    for index, line in enumerate(lines):
        if global_only and (line.strip().startswith('[') or (slot is not None and index >= slot)):
            in_section = True
        if owns(line) and not in_section:
            if first_removed is None:
                first_removed = len(kept)
            if slot is not None and index < slot:
                slot -= 1
            continue
        kept.append(line)

    fresh = slot is None
    if fresh:
        slot = first_removed if first_removed is not None else default_slot(kept)
    block = [begin, *body, end]
    if fresh:
        if slot > 0 and kept[slot - 1].strip():
            block.insert(0, '')
        if slot < len(kept) and kept[slot].strip():
            block.append('')
    return '\n'.join(kept[:slot] + block + kept[slot:]) + '\n'


def first_section(lines: list[str]) -> int:
    for index, line in enumerate(lines):
        if line.strip().startswith('['):
            return index
    return len(lines)


def walker_css(palette: dict, text: str) -> str:
    names = '|'.join(re.escape(name) for name in WALKER_COLORS)
    pattern = re.compile(rf'^\s*@define-color\s+({names})\s')
    return replace_block(
        text,
        f'/* leo-theme:begin ({GENERATED_BY}) */',
        '/* leo-theme:end */',
        walker_block(palette),
        lambda line: bool(pattern.match(line)),
        lambda lines: 0,
    )


def mako_config(palette: dict, text: str) -> str:
    pattern = re.compile(rf"^\s*({'|'.join(MAKO_KEYS)})\s*=")
    return replace_block(
        text,
        f'# leo-theme:begin ({GENERATED_BY})',
        '# leo-theme:end',
        mako_block(palette),
        lambda line: bool(pattern.match(line)),
        first_section,
        global_only=True,
    )


def ghostty_config(palette: dict, text: str) -> str:
    pattern = re.compile(r'^\s*theme\s*=')
    return replace_block(
        text,
        f'# leo-theme:begin ({GENERATED_BY})',
        '# leo-theme:end',
        ghostty_block(palette),
        lambda line: bool(pattern.match(line)),
        len,
    )


def targets(root: Path) -> list[tuple[Path, Callable[[dict, str], str], bool]]:
    """(path, render(palette, current_text), whole_file)."""
    return [
        (root / 'leo/theme/hyprland.conf', lambda palette, _text: hyprland_conf(palette), True),
        (root / 'leo/theme/hyprlock.conf', lambda palette, _text: hyprlock_conf(palette), True),
        (root / 'leo/login/theme.conf.user', lambda palette, _text: login_config(palette), True),
        (root / 'walker/themes/leo/style.css', walker_css, False),
        (root / 'mako/config', mako_config, False),
        (root / 'ghostty/config', ghostty_config, False),
    ]


def render_all(palette: dict, root: Path) -> list[tuple[Path, str, str]]:
    """Return (path, current_text, new_text) for every target that exists or is generated whole."""
    results = []
    for path, render, whole_file in targets(root):
        try:
            current = path.read_text()
        except FileNotFoundError:
            if not whole_file:
                print(f'skipping {path}: file does not exist', file=sys.stderr)
                continue
            current = ''
        results.append((path, current, render(palette, current)))
    return results


def write_file(path: Path, text: str) -> None:
    """Replace the real file (following symlinks) atomically."""
    real = path.resolve()
    real.parent.mkdir(parents=True, exist_ok=True)
    temporary = real.with_name(f'.{real.name}.tmp')
    temporary.write_text(text)
    if real.exists():
        temporary.chmod(real.stat().st_mode & 0o7777)
    os.replace(temporary, real)


RELOAD_NOTES = """\
Hyprland reloads its config automatically.
Hyprlock picks up the theme next time you lock.
SDDM: run system-login-install.sh to update its system-wide theme and wallpaper.
It takes effect at the next login; do not restart SDDM during your session.
Ghostty: press ctrl+shift+, in open windows (new windows pick the theme up).
Walker: restart it with
  pkill -x walker; uwsm-app -- walker --gapplication-service & disown"""


def reload_apps() -> None:
    try:
        result = subprocess.run(['makoctl', 'reload'], capture_output=True, text=True, timeout=5, check=False)
        ok = result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        ok = False
    print('Mako reloaded.' if ok else 'makoctl reload failed; restart mako manually.')
    print(RELOAD_NOTES)


def parse_args(argv: list[str]) -> tuple[Path | None, bool, bool] | None:
    palette_path, check, reload = None, False, False
    args = iter(argv)
    for arg in args:
        if arg == '--check':
            check = True
        elif arg == '--reload':
            reload = True
        elif arg == '--palette':
            value = next(args, None)
            if value is None:
                return None
            palette_path = Path(value).expanduser()
        elif arg.startswith('--palette='):
            palette_path = Path(arg.split('=', 1)[1]).expanduser()
        else:
            return None
    return palette_path, check, reload


def main(argv: list[str]) -> int:
    parsed = parse_args(argv)
    if parsed is None:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    palette_path, check, reload = parsed
    root = config_home()
    palette_path = palette_path or root / 'leo/theme/palette.json'

    try:
        palette = load_palette(palette_path)
        results = render_all(palette, root)
    except (PaletteError, ValueError) as error:
        print(f'system-theme-apply: {error}', file=sys.stderr)
        return 1

    changed = [(path, current, new) for path, current, new in results if current != new]
    if check:
        for path, current, new in changed:
            sys.stdout.writelines(difflib.unified_diff(
                current.splitlines(keepends=True), new.splitlines(keepends=True),
                fromfile=f'{path} (on disk)', tofile=f'{path} (from palette)',
            ))
        if changed:
            print(f'{len(changed)} file(s) out of date with {palette_path}')
            return 1
        print('All theme outputs are up to date.')
        return 0

    for path, _current, new in changed:
        write_file(path, new)
        print(f'updated {path}')
    if not changed:
        print('All theme outputs are up to date.')
    if reload:
        reload_apps()
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
