#!/usr/bin/env bash
# Setup a new session
# vim
tmux new-window -n dev
tmux send-keys 'vim' Enter

# opencode
tmux new-window -n opencode
tmux send-keys 'opencode' Enter

# shell
tmux new-window -n exec

# Select vim
tmux select-window -t dev
