#!/usr/bin/env bash
# Setup a new session
# vim
tmux new-window -n dev
tmux send-keys 'vim' Enter

# pi
tmux new-window -n agent
tmux send-keys 'pi' Enter

# shell
tmux new-window -n exec

# Select vim
tmux select-window -t dev
