#!/usr/bin/env bash
# Dev tmux window layout (vim + opencode + shell)
tmux rename-window "dev"
tmux send-keys 'vim' Enter
# Vertical split
tmux split-window -h -l 80
tmux send-keys 'opencode' Enter
# Horizontal split
tmux split-window -v -l 10
# Select vim pane
tmux select-pane -L
