#!/usr/bin/env bash
directories="$HOME/gitrepo $HOME/"
script=""
if [ "$USER" == "13lbise" ]; then
    # Work user
    directories="$HOME/andromeda $directories"
    # Run script to setup new session
    script="dev-tmux"
fi


if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find $directories -mindepth 1 -maxdepth 1 -type d -not -path "*/.*" | echo -e "$HOME\n$(</dev/stdin)" | fzf-tmux -p -w 35% -h 38% --reverse)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected $script
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected $script
fi

# Switch or attach to the session
if [ -z $TMUX ]; then
    # From outside tmux
    tmux attach -t $selected_name
else
    # From within tmux
    tmux switch-client -t $selected_name
fi
