#!/usr/bin/env bash
if [[ $# -eq 1 ]]; then
    selected=$1
else
    directories="$HOME/gitrepo $HOME/"
    if [ "$USER" == "13lbise" ]; then
        directories="$HOME/andromeda $directories"
    fi
    selected=$(find $directories -mindepth 1 -maxdepth 1 -type d -not -path "*/.*" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

# Create script to CD into directory upon creating session
#tmpfile="/tmp/tmux-sessionizer.$USER"
#chmod +x $tmpfile
#echo "cd $selected" > $tmpfile

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

echo $selected

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    echo "create new session s"
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    echo "create new session ds"
    tmux new-session -ds $selected_name -c $selected
fi

echo $selected_name
echo $selected
if [ -z $TMUX ]; then
    # From outside tmux
    tmux attach -t $selected_name
else
    # From within tmux
    tmux switch-client -t $selected_name
fi
